# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: vuepress node

on:
  push:
    branches: 
      - main

jobs:
  download-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      # - uses: actions/download-artifact@v2
      #   with:
      #     path: ~/docs/note

      # 下载 git submodule
      - name: download submodule
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive

      # 更新 git submodule
      - name: update submodule    
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule foreach git pull

       # 使用 node:10
      - name: use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      # npm install
      - name: npm install and build
        run: |
          npm install
          npm run docs:build
        env:
          CI: true
          
      # Deploy
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.0.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_TOKEN }}
          ARGS: "-avz --delete"
          REMOTE_HOST: ${{ secrets.ALIYUN_HOST }}
          REMOTE_USER: "root"
          # REMOTE_PORT: ${{ secrets.ALIYUN_PORT }}
          SOURCE: "docs/.vuepress/dist/"
          TARGET: "/srv/www/note-press"